### PR TITLE
TransactionUndoStorage tests close the conn and db

### LINKED ISSUE #138: ZODB.tests.TransactionalUndoStorage leaks a DB and open storage
See https://github.com/newtdb/db/pull/2#issuecomment-275168836

Opening as a reminder to myself to review and submit a PR.

### PR DESCRIPTION
**Pull request by jamadden**
This fixes leaking connections (relying on the GC to close them).

Tested with RelStorage.

Fixes #138 

Addition of try/finally blocks only. May be easier to view with ?w=0

### CODE REVIEW

**Comment by jamadden** [comment]
Could this land for 5.2?

**Comment by jamadden** [comment]
Thanks!

**Comment by jimfulton** [comment]
Is there anything else you want me to wait for?

**Comment by jamadden** [comment]
Not me. Thank you for asking.

**Pull request merged**
