### PR TITLE
Add badges to README.

### PR DESCRIPTION
**Pull request by tseaver**

### CODE REVIEW

**Comment by jamadden** [comment]
Should some of those (the version-related ones, at least) be also added to doc/index.rst? The same text about supported versions is repeated there.

**Comment by tseaver** [comment]
Sorry for the too-quick merge!

I think they are more useful in the "project browse" mode of a Github README than in docs.

**Comment by jamadden** [comment]
There's also the coverage badge which might be useful in a development context:
```
.. image:: https://coveralls.io/repos/github/zopefoundation/ZODB/badge.svg
:target: https://coveralls.io/github/zopefoundation/ZODB

```

**Comment by jamadden** [comment]
> I think they are more useful in the "project browse" mode of a Github README than in docs.

Fair enough. I have no strong feelings one way or the other ("If we don't make it, tell my wife...hello.")

**Comment by tseaver** [comment]
I just added the coverage badge on the trunk.

**Pull request merged**
