### PR TITLE
Release version 5.6.0

### LINKED ISSUE #308: Release new version?
It's been a year and a half since the last version was released and in that time transaction has released a new version which breaks the tests in the latest release of ZODB. Any chance we can get a new version released sometime soon?

### PR DESCRIPTION
**Pull request by jmuchemb**
Closes #308.

### CODE REVIEW

**Comment by jamadden** [comment]
I would assume that those changes are made by `zest.releaser` when actually publishing the release to PyPI. At least, that's the most common workflow for zopefoundation projects that I've seen.

**Comment by jmuchemb** [comment]
I didn't know zest.releaser and what would it do in addition to

    python setup.py sdist
    twine upload -s dist/...

?
Of course, I would also push an extra "svb" commit by mimicking what other devs do here.

**Comment by jmuchemb** [comment]
... and a tag the same way as the previous one was done.

**Comment by jamadden** [comment]
zest.releaser handles the entire release process, including:

- Updating dates in changelog
- Changing version numbers before and after the release
- Creating the new empty section in the changelog
- making the tag
- uploading sdist and wheel.
- pushing the tag upstream

It's highly recommended and ensures nothing gets forgotten.

**Comment by mgedmin** [comment]
This PR is not helpful: it contains about 1/3rd of the release process (pre-release changelog and version update), and shouldn't be merged without actually doing the other 2/3rds (dist/wheel build and upload, post-release changelog and version update).  

Only three people are allowed to do the PyPI upload step, so you need to ask one of them to make the release:

> Maintainers: J1m, jm, tseaver

**Comment by mgedmin** [comment]
(Also, 5.6.0 should be a git tag, not a git branch.  What does git do when you try to create a tag with the same name as the branch?)

**Comment by mgedmin** [comment]
@jmuchemb, are you user **jm** on PyPI?  If yes, just run zest.releaser's `fullrelease` command.  It nicely shows everything it's doing (git diff) and asks for confirmation before running any commands (git commit; twine upload, git tag, git push).

**Comment by jmuchemb** [comment]
> (Also, 5.6.0 should be a git tag, not a git branch. What does git do when you try to create a tag with the same name as the branch?)

The branch would have be removed once this PR is merged and then I'd have tagged.

And for the previous release, there was a PR.

> @jmuchemb, are you user jm on PyPI?

yes

I don't like having such kind tool but I didn't want to discuss so I used fullrelease. Things didn't go perfectly. I was not offered to possibility to sign things (pypi & tag). It also failed at the end because I was detached HEAD.

But everything should be fine now.

**Comment by mgedmin** [comment]
zest.releaser is not mandatory, just convenient.  There used to be a documented release process in a text file in svn.zope.org (no idea where it ended up now, likely nowhere), and zest.releaser automated it.

(I myself use only parts of the release process for the packages I maintain outside zopefoudnation, because I want to have additional pre-release checks, and I also want to create signed tags.  So I do zest.releaser's `prelelease` (to update & commit changelog and version), then manual setup.py sdist bdist_wheel && twine upload && git tag -s, and then I use zest.releaser's `postrelease` to update & commit changelog and version again, and to push the commits and the tag.)

**Pull request closed without merging**
