### PR TITLE
Add support for Python 3.11

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Lots of changes, but 99 percent is automatic by isort. No real changes needed to far.

### CODE REVIEW

**Review by icemac — APPROVED** [review]
LGTM from quickly scanning through the diff.
(I assume it is mostly generated by tools.)

**Comment by dataflake** [comment]
Please hold on with this PR:

There are a few larger PRs in the work and they will take more time. If you put all those "cosmetic" changes from isort and flake8 on master it will become a huge pain to integrate those branches.

My suggestion: Re-do without flake8 and only the minimum required changes for Python 3.11 support. Linting can be added later, after everything else is done.

**Comment by dataflake** [comment]
Oops, I misspoke: The big PRs are actually for ZEO, not for ZODB. Sorry for the confusion. This looks fine, go ahead.

**Review by dataflake — APPROVED** [review]

**Comment by mauritsvanrees** [comment]
Merged. Thanks for the reviews.
A release would probably be good, but this PR and the other changes since the previous release only touch meta files and tests, so no hurry here. I am just happy to know that ZODB works with 3.11.

I did have a quick look at ZEO yesterday, but already decided not to touch it currently for the reasons Jens mentions.

**Comment by dataflake** [comment]
ZODB 5.8.0 is now released.

**Pull request merged**
