### PR TITLE
Load calls load before

### PR DESCRIPTION
**Pull request by jimfulton**
This is a cleanup PR that changes the storage ``load`` implementations to call ``loadBefore``. Eventually, these load implementations will go away, but lots of tests use them, so ...

A follow on PR will change the tests in ZODB to not call load. :)

### CODE REVIEW

**Comment by tseaver** [comment]
Should `ZODB.utils.load_current` be private?

**Comment by jimfulton** [comment]
I don't think so, but I don't have a strong opinion at this point. Do you think it should be private?

**Comment by jimfulton** [comment]
@tseaver ?

**Comment by tseaver** [comment]
Dunno, I was just seeing it newly added, and didn't know whether we wanted/expected outside callers to use it:  if so, it could use a docstring.

**Comment by jimfulton** [comment]
Docstring added

**Comment by jimfulton** [comment]
Travis is green :)

**Comment by tseaver** [comment]
LGTM

**Pull request merged**
