### PR TITLE
buildout: Fix CI

### PR DESCRIPTION
**Pull request by navytux**
~~Else it is failing as:~~
~~...~~
~~(see e.g. https://travis-ci.com/github/zopefoundation/ZODB/jobs/499760337)~~

Fix buildout-related CI issues.

Suggested by @d-maurer.

### CODE REVIEW

**Review by d-maurer — APPROVED** [review]

**Comment by d-maurer** [comment]
The `docutils` version problem apparently exists for Python 3 as well. This means that the `docutils` version restriction should go into the `versions` (rather than the `versions:python2`) section.

**Comment by navytux** [comment]
> The `docutils` version problem apparently exists for Python 3 as well. This means that the `docutils` version restriction should go into the `versions` (rather than the `versions:python2`) section.

Thanks, @d-maurer. Let's make another try with that approach (https://github.com/zopefoundation/ZODB/pull/346/commits/82bee274ecb2f039a3a2e200f8c9eb93f887a0dd).

**Comment by navytux** [comment]
Another thing is to fix requirements for pygments. From https://github.com/zopefoundation/ZODB/pull/346/commits/5b8e2dc12924fa29ccf76b0eb8e63c594d433824:

---- 8< ----
Commit 75c703f (Security fix documentation dependencies (#342)) changed
requirements for pygments from

    # pygments 2.6 stops the support for python2
    pygments<2.6

to

    # Silence dependabot claiming a security issue in older versions:
    pygments >= 2.7.4

However this broke CI for python2, as sphinx now fails to install:

    Collecting Sphinx
      Using cached Sphinx-1.8.5-py2.py3-none-any.whl (3.1 MB)
    ERROR: Could not find a version that satisfies the requirement pygments>=2.7.4 (from -r doc/requirements.txt (line 3)) (from versions: 0.5, 0.5.1, 0.6, 0.7, 0.7.1, 0.8, 0.8.1, 0.9, 0.10, 0.11, 0.11.1, 1.0, 1.1, 1.1.1, 1.2, 1.2.1, 1.2.2, 1.3, 1.3.1, 1.4, 1.5, 1.6rc1, 1.6, 2.0rc1, 2.0, 2.0.1, 2.0.2, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.2.0, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 2.4.2, 2.5.1, 2.5.2)
    ERROR: No matching distribution found for pygments>=2.7.4 (from -r doc/requirements.txt (line 3))
    The command "if [[ $TRAVIS_PYTHON_VERSION != pypy3* ]]; then pip install --upgrade --requirement doc/requirements.txt; fi" exited with 1.

(see e.g. https://travis-ci.com/github/zopefoundation/ZODB/jobs/499836548)

Try to fix that by bringing back requirement for `pygments < 2.6` on
python2.
---- 8< ----

/cc @icemac

**Comment by navytux** [comment]
CI is fine. @d-maurer, do you think it is ok now?

**Comment by d-maurer** [comment]
> CI is fine. @d-maurer, do you think it is ok now?
As the CI tests pass, it is ok.

**Comment by navytux** [comment]
Thanks, @d-maurer.

**Comment by icemac** [comment]
Sorry for being late on the party: allowing `pygments<2.6` for Python 2 creates a security alert from Dependabot which I tried to silence by forcing `pygments >= 2.7.4`. I dismissed the alert because it is not relevant in case of the documentation. Let's see if this helps.

**Comment by navytux** [comment]
@icemac, thanks for sharing the context. Hopefully it is indeed ok, as we use pygments to prepare documentation only from trusted commited-to-ZODB sources.

**Comment by icemac** [comment]
@navytux As @jamadden commented in #342, ignoring the problem should be okay, as there is no plausible attack vector.

**Pull request merged**
