### PR TITLE
Fix `racetest` problems

### PR DESCRIPTION
**Pull request by d-maurer**
This PR fixes problems with the `racetest`s observed during work on "https://github.com/zopefoundation/ZEO/pull/225".

It uses daemon (rather than normal) threads to avoid deadlock on shutdown when one of the test threads has not finished. It treats the failure for a test thread to finish as a test failure.

### CODE REVIEW

**Comment by dataflake** [comment]
@d-maurer I am currently fixing the GHA configuration-related errors and deprecation warnings on `master` and will let you know when I am done, then you can merge the changes here.

**Comment by dataflake** [comment]
If you merge in https://github.com/zopefoundation/ZODB/commit/9ffc59e5bd3eb68d8e43f79265e45d245b832f76 you should get the py35/py36 tests back and get rid of all the deprecation warnings.

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2023-2-3 03:26 -0800:
>If you merge in https://github.com/zopefoundation/ZODB/commit/9ffc59e5bd3eb68d8e43f79265e45d245b832f76 you should get the py35/py36 tests back and get rid of all the deprecation warnings.

Thank you for your help!

**Review by navytux — APPROVED** [review]
Thanks, Dieter. I agree it is better to explicitly fail if thread join does not succeed.

**Pull request merged**
